name: Rust CI (MacOS)

on:
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- --deny warnings
      - run: cargo build --verbose
      - run: cargo test --verbose