name: Rust CI (Linux)

on:
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev cmake clang
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- --deny warnings
      - run: cargo build --verbose
      - run: cargo test --verbose